### ISSUE TITLE
code doesn't work

### ISSUE THREAD

**Issue by wanzhixiao** [LeiBAI/STG2Seq#2]
as title, the code is doesn't work，would you please release a runable version?

**Comment by xiang526** [comment]
您好，我在运用taxibj数据运行代码，提示ValueError: Cannot feed value of shape (32, 1024, 2, 8) for Tensor 'Train/model/c_inp:0', which has shape '(?, 8, 32, 32, 2)'，我的邮箱是2628029699@qq.com，麻烦您能给我一些指导解决该bug

**Comment by LeiBAI** [comment]
> as title, the code is doesn't work，would you please release a runable version?

Thanks for your interest. As noted in the paper, the graph can be defined according to similarity or other methods. You can just add your graph definition method and the code should be runnable. If you have other problems, please raise a new issue.

**Comment by LeiBAI** [comment]
You can reshape the data from (32, 1024, 2, 8) to (32, 32, 32, 2, 8) and then permute to (32, 8, 32, 32, 2). As I have switched to Pytorch, I will release a Pytorch version of the code later.

**Comment by xiang526** [comment]
> You can reshape the data from (32, 1024, 2, 8) to (32, 32, 32, 2, 8) and then permute to (32, 8, 32, 32, 2). As I have switched to Pytorch, I will release a Pytorch version of the code later.

Thank you for your reply. Looking forward to your Pytorch version of the code. I will try to modify the code as you say.

**Comment by xiang526** [comment]
when I modified the coed as you say,a new bug arised:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeiBAI/STG2Seq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:33
收件人:&nbsp;"LeiBAI/STG2Seq"<STG2Seq@noreply.github.com&gt;;
抄送:&nbsp;"goodluck"<2628029699@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LeiBAI/STG2Seq] code doesn't work (#2)





 
You can reshape the data from (32, 1024, 2, 8) to (32, 32, 32, 2, 8) and then permute to (32, 8, 32, 32, 2). As I have switched to Pytorch, I will release a Pytorch version of the code later.

**Comment by xiang526** [comment]
I am very sorry to say when I modified the coed as you say,a new bug arised. Because your paper inspired me,&nbsp;I am&nbsp;Urgently looking forward to&nbsp;if you could kindly send me t&nbsp;a Pytorch version of the code.&nbsp;
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeiBAI/STG2Seq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:33
收件人:&nbsp;"LeiBAI/STG2Seq"<STG2Seq@noreply.github.com&gt;;
抄送:&nbsp;"goodluck"<2628029699@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LeiBAI/STG2Seq] code doesn't work (#2)





 
You can reshape the data from (32, 1024, 2, 8) to (32, 32, 32, 2, 8) and then permute to (32, 8, 32, 32, 2). As I have switched to Pytorch, I will release a Pytorch version of the code later.

**Comment by xiang526** [comment]
您好：
&nbsp; &nbsp; &nbsp; 我最近阅读了您的论文STG2Seq: Spatial-temporal Graph to Sequence Model for Multi-step Passenger Demand Forecasting，并在您的github中下载了该论文的代码，在您github issue的回复下跑通了代码，但运行结果与您在论文中的评价指标值相差甚大，我在想是不是我在处理代码错误时，处理的不够全面，才会导致这样的差别。您之前在github中回复说要提供pytorch版本，我想在用您的pytorch版本再试试，您能给我分享下您的代码和数据吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeiBAI/STG2Seq"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:33
收件人:&nbsp;"LeiBAI/STG2Seq"<STG2Seq@noreply.github.com&gt;;
抄送:&nbsp;"goodluck"<2628029699@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [LeiBAI/STG2Seq] code doesn't work (#2)





 
Closed #2.
